name: Validation
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v7
      with:
        push: false
    - uses: actions/upload-pages-artifact@v3
      with:
        path: "."
